#server:
#  port: ${PORT:8080}
#
#eureka:
#  instance:
#    hostname: ${HOSTNAME:localhost}
#    nonSecurePort: ${server.port}
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
